import pdfplumber
import chromadb
import requests
import os
import hashlib
from pathlib import Path
from LLM.keys import GROQ_API_KEY


def extract_text_from_pdf(pdf_path: str) -> str:
    """Extract all text from a PDF file."""
    text = ""
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + "\n\n"
    return text.strip()


def chunk_text(text: str, chunk_size: int = 800, overlap: int = 150) -> list[str]:
    """Split text into overlapping chunks by character count."""
    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end]
        if chunk.strip():
            chunks.append(chunk.strip())
        start += chunk_size - overlap
    return chunks


def build_collection_from_reports(report_paths: list[str]) -> chromadb.Collection:
    """
    Build a ChromaDB in-memory collection from a list of PDF report paths.
    Uses ChromaDB's default embedding function (all-MiniLM-L6-v2).
    """
    client = chromadb.Client()

    # Deterministic collection name based on file set to allow caching
    paths_hash = hashlib.md5(
        "|".join(sorted(report_paths)).encode()
    ).hexdigest()[:12]
    collection_name = f"reports_{paths_hash}"

    # Delete if already exists to rebuild fresh
    existing = [c.name for c in client.list_collections()]
    if collection_name in existing:
        client.delete_collection(collection_name)

    collection = client.create_collection(
        name=collection_name,
        metadata={"hnsw:space": "cosine"},
    )

    all_docs = []
    all_ids = []
    all_meta = []

    for path in report_paths:
        filename = Path(path).name
        text = extract_text_from_pdf(path)
        if not text:
            continue
        chunks = chunk_text(text)
        for i, chunk in enumerate(chunks):
            doc_id = hashlib.md5(f"{filename}_{i}".encode()).hexdigest()
            all_docs.append(chunk)
            all_ids.append(doc_id)
            all_meta.append({"source": filename, "chunk_index": i})

    if all_docs:
        # ChromaDB accepts batches up to ~5000
        batch_size = 500
        for start in range(0, len(all_docs), batch_size):
            end = start + batch_size
            collection.add(
                documents=all_docs[start:end],
                ids=all_ids[start:end],
                metadatas=all_meta[start:end],
            )

    return collection


def query_reports(collection: chromadb.Collection, question: str, n_results: int = 6) -> str:
    """
    Retrieve relevant chunks from the collection and generate an answer
    using the Groq LLM.
    """
    results = collection.query(query_texts=[question], n_results=n_results)

    # Build context from retrieved chunks
    context_parts = []
    for doc, meta in zip(results["documents"][0], results["metadatas"][0]):
        source = meta.get("source", "unknown")
        context_parts.append(f"[Source: {source}]\n{doc}")
    context = "\n\n---\n\n".join(context_parts)

    prompt = f"""You are a professional data analyst assistant. The user has uploaded reports 
generated by our analytics platform. Answer the user's question based ONLY on the 
information found in the report excerpts below. If the information is not available 
in the provided context, clearly state that.

Be precise, cite specific numbers and findings from the reports when available, 
and structure your answer clearly.

### REPORT EXCERPTS ###
{context}

### USER QUESTION ###
{question}

### ANSWER ###"""

    response = requests.post(
        "https://api.groq.com/openai/v1/chat/completions",
        headers={
            "Authorization": f"Bearer {GROQ_API_KEY}",
            "Content-Type": "application/json",
        },
        json={
            "model": "llama-3.3-70b-versatile",
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.3,
            "max_tokens": 2048,
        },
    )

    response_json = response.json()

    if "choices" not in response_json:
        return f"Error from LLM API: {response_json.get('error', {}).get('message', 'Unknown error')}"

    return response_json["choices"][0]["message"]["content"]


def get_pdf_files_from_folder(folder_path: str) -> list[str]:
    """Return all PDF file paths from a folder."""
    folder = Path(folder_path)
    if not folder.is_dir():
        return []
    return [str(p) for p in sorted(folder.glob("*.pdf"))]
